108 services
HadarRose/C102 pull request #9
Opened 2020-07-28 15:15 UTC by HadarRose

- Created services: TwitterCreationService, TwitterExceptionHandlerService, TwitterResourceService, ConfigService
- Removed service functionalities from original classes 
- Refactored ExceptionHandler to be TwitterExceptionHandlerService
- Updated tests to fit new architecture

2020-07-28 15:31 UTC, kev-chan requested changes
I want you to think about how others may want to reuse your service, namely TwitterService.  Are there any assumptions you are making and if so, please make changes.  If not, let's talk when you are out of ideas.

2020-07-28 15:34 UTC, kev-chan commented
for more context, other developers are code.  Why separate out between Resources and Services in the first place?

2020-07-28 15:50 UTC, HadarRose commented
@kev-chan in response to your comments: I think I understand what you mean. If I understand correctly, the point of the refactoring should have been to allow TwitterRequestResource to be independent of the way we choose to reach Twitter.  Meaning that if we chose to make our own calls to Twitter API w/o twitter4j, for example, all we'd have to change is the service, not both the service and the resource. I'll make the Resource class completely independent of twitter4j.

2020-07-30 17:34 UTC, kev-chan requested changes

2020-07-30 17:34 UTC, kev-chan commented on src/main/java/configuration/ApplicationConfiguration.java
> +import model.TwitterKeys;
package you typically want <something>.<somethig> and not just model.TwitterKeys.  The extended package makes it much less likely to clash with other dependencies.  This applies to all your code.

2020-07-30 17:34 UTC, kev-chan commented on src/main/java/model/TwitterKeys.java
> +public class TwitterKeys {
why the model package? when this is an extension of the configuration

2020-07-30 17:34 UTC, kev-chan commented on src/test/java/services/twitter4j/TwitterResourceExceptionTest.java
> +        TwitterException exception = mock(TwitterException.class);
for future reference but no need to change now
you could probably simplify with the following
TwitterExceotion exception = new TwitterException();
exception.setStatusCode(...)
it's simpler w/o the mocks and you've got this pattern in multiple places

2020-07-30 17:34 UTC, kev-chan commented on src/test/java/resources/TwitterRequestResourceTest.java
> +        mockedResourceServices = mock(TwitterResourceService.class);
good use of mock

2020-07-30 17:34 UTC, kev-chan commented on src/main/java/services/twitter4j/TwitterResourceService.java
> +        TwitterCreationService twitterCreationService = new TwitterCreationService(twitterKeys);
do you actually need a twitter creation service?

2020-07-30 19:31 UTC, merged